networks:
  gitea:
    external: false
services:
  gitea-server:
    image: gitea/gitea:1.20.4
    container_name: gitea
    environment:
      - USER_UID=1001
      - USER_GID=1001
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea-db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA_DOMAIN=git.dino-technologies.nl
      - GITEA_SSH_DOMAIN=dino-technologies.nl
      - GITEA_SSH_PORT=3222
    restart: unless-stopped
    networks:
      - home_network_default
      - gitea
    volumes:
      - /mnt/media_server/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 3222:22
    depends_on:
      - gitea-db
  gitea-db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - /mnt/media_server/gitea_db:/var/lib/mysql
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    privileged: true
    networks:
      - home_network_default
    ports:
      - 9080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nexus:
    image: sonatype/nexus3:latest
    restart: unless-stopped
    container_name: nexus
    networks:
      - home_network_default
    ports:
      - 8081:8081
  socat:
    image: alpine/socat:latest
    restart: unless-stopped
    container_name: socat
    networks:
      - home_network_default
    ports:
      - 127.0.0.1:2376:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
