networks:
  gitea:
    external: false
  home_network_default:
    external: true
services:
  gitea-server:
    image: gitea/gitea:1.20.4
    container_name: gitea
    environment:
      - USER_UID=1001
      - USER_GID=1001
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea-db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA_DOMAIN=git.dino-technologies.nl
      - GITEA_SSH_DOMAIN=dino-technologies.nl
      - GITEA_SSH_PORT=3222
    restart: unless-stopped
    networks:
      - home_network_default
      - gitea
    volumes:
      - /mnt/media_server/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 3222:22
    depends_on:
      - gitea-db
  gitea-db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - /mnt/media_server/gitea_db:/var/lib/mysql

